
sam_checkpoint: "/home/ekanshgupta92/checkpoints/sam2_hiera_large.pth"
sam_model_type: "hiera_l"
textvqa_path: "/home/ekanshgupta92/textvqa/textvqa.json"
textvqa_image_dir: "/home/ekanshgupta92/textvqa/images"
coco_dir: "/home/ekanshgupta92/coco/train2017"
coco_annotations: "/home/ekanshgupta92/coco/annotations/instances_train2017.json"
max_scenes: 1
max_textvqa: 1
max_coco: 1
epochs: 3
batch_size: 16
gradient_accumulation_steps: 2
learning_rate: 2e-5
save_steps: 200
output_dataset: "vqa_dataset.json"
fine_tune_output: "trained_vlm"
